/////// THIS WEEK LESSONE /////////


////DAY 1

let Username="Javascript";
//var
var MYname ="Alghalia";


//let
//  let Myname= "Alghalia";

//implicit

let ALGHALIA ;
ALGHALIA="ALGHALIARASHED" ;

console.log(ALGHALIA);

//explicit

let Alghalia ="AlghaliaRashed";

console.log(Alghalia)


let _username;
let userName;
let $username;

// let My_age;
let My_Age;

const mY_name="Alghalia";


const Id ="137297";
console.log(ID)



const My_age=2006;
console.log(My_age);

let Myname;
Myname="Alghalia Rashed";
console.log(Myname);





//// DAY 2

// OBJECTS
let testObjects_1 ={
    num$1:44,
    str$1:"text",
    boo$1:true ,
    
}
console.log(`${typeof testObjects_1}:${testObjects_1}`);
console.log(testObjects_1 .str$1);
console.log(testObjects_1 .num$1);
 console.log(testObjects_1 .boo$1);

 



///// DAY 3 

//boolean
let text1=false;
let text2=true;

console.log(text1);
console.log(text2);
console.log(typeof text1);


//symbol type
let ID=Symbol("ID");

console.log(ID);
console.log(typeof ID);


//Null type
let text3= null;
console.log(text3);
console.log(typeof text3);

//undefiend
let text5;
console.log(text5);
console.log(typeof text5);


//number
//intager
let x1=100;
console.log(x1)
console.log(typeof x1);


//double
let X=2.1;
console.log(X);
console.log(typeof X);


//Bigint
let bigl=12345678910n;
console.log(bigl);
console.log(typeof bigl);

let x0 =20n-10n;
console.log(x0);



//string
let massage= "Hello";
console.log(massage);

let massage2="im Alghalia";
console.log(massage2);

let massage3="whats your name?";
console.log(massage3);



//string
massage4 = "text"-"text";
console.log(massage4);
console.log(typeof massage4);

let massage5 = "100"-"50";
console.log(massage5);
console.log(typeof massage5);

let massage6 = "100"+ "50";
console.log(massage6);
console.log(typeof massage6);



//الاستبدال المنطقي inter polation
let country = "Riyadh";
let continet ="Alghalia";
console.log( "$(country) locatied in $(continet) ");


//string propreti
let StR ="java script language"
console.log(str.charAt(5));

//slice
console.log(str.slice(0,11));


////split
console.log(str.split(" "));






///// DAY 4


//converstim types
let str = String();
let num = Number();
let bool = Boolean();


//string to sring
const Str ="Text";
const StrToStr = String (Str);
console.log(`${typeof Str}:${Str}`);
console.log(`${typeof StrToStr}:${StrToStr}`);

//Num To Sring
const Num_1 =20;
const NumTOStr = String (Num_1);
console.log(`${typeof Num_1 }:${Num_1}`);
console.log(`${typeof NumTOStr}:${NumTOStr}`);


//boolean To String
const Bool_1 =true;
const BoolToStr = String(Bool_1);
console.log(`${typeof Bool_1}:${Bool_1}`);
console.log(`${typeof BoolToStr}:${BoolToStr}`);

//undefined To String 
const Un = undefined
const UnToStr =String (Un);
console.log(`${typeof Un}: ${Un}`);

//Null To String
const NUll  = null
const NullToStr =String (NUll);
console.log(`${typeof NUll} :${NUll}`);
console.log('$(typeof NUllToStr):$(NUllToStr)');


///Number To Number
const N_um =4;
const NumToNum = Number (N_um);
console.log(`${typeof N_um }:${NumToNum}`);
console.log(`${typeof NumToNum}:{NumToNum}`);

//Bigint To String


//Sting To Number
const STR = 7;
const STRTONUM = Number (7);
console.log(`${typeof STR}:${STRTONUM}`);
console.log(`${typeof STRTONUM}:${STRTONUM}`);

/// Boolean To Boolean
const Bool_11 =true;
const BoolToBool = Boolean(Bool_11);
console.log(`${typeof Bool_11}:${Bool_11}`);
console.log(`${typeof BoolToBool}:${BoolToBool}`);

///Num To Boolean
const Num_4 =2
const NumToBool = Boolean (Num_4);
console.log(`${typeof Num_4}:${Num_4}`);
console .log (`${typeof NumToBool}:${NumToBool}`);

//Undefiend To Boolean
const UN =undefined
const UNToBool = Boolean (UN);
console.log(`${typeof UN}:${UN}`);
console .log (`${typeof UNToBool}:${UNToBool}`);

//Null To Boolean
const Null = null
const NullToBool = Boolean (Null);
console.log(`${typeof Null}:${Null}`);
console .log (`${typeof NullToBool}:${NullToBool}`);

//String To Boolean
const STr = "text1"
const StrllToBool = String (STr);
console.log(`${typeof STr}:${STr}`);
console .log (`${typeof StrllToBool}:${StrllToBool}`);

//Math 
let plus =100-"50";
console.log(plus);

let main = 100+"50";
console.log (main);

